
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(600, 650))
        MainWindow.setMaximumSize(QtCore.QSize(600, 650))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelName = QtWidgets.QLabel(self.centralwidget)
        self.labelName.setGeometry(QtCore.QRect(20, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.labelName.setFont(font)
        self.labelName.setObjectName("labelName")
        self.labelCourse = QtWidgets.QLabel(self.centralwidget)
        self.labelCourse.setGeometry(QtCore.QRect(20, 150, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.labelCourse.setFont(font)
        self.labelCourse.setObjectName("labelCourse")
        self.labelCredits = QtWidgets.QLabel(self.centralwidget)
        self.labelCredits.setGeometry(QtCore.QRect(480, 160, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.labelCredits.setFont(font)
        self.labelCredits.setObjectName("labelCredits")
        self.labelGrade = QtWidgets.QLabel(self.centralwidget)
        self.labelGrade.setGeometry(QtCore.QRect(290, 160, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.labelGrade.setFont(font)
        self.labelGrade.setObjectName("labelGrade")
        self.classInput_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.classInput_1.setGeometry(QtCore.QRect(20, 190, 201, 31))
        self.classInput_1.setObjectName("classInput_1")
        self.classInput_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.classInput_2.setGeometry(QtCore.QRect(20, 230, 201, 31))
        self.classInput_2.setObjectName("classInput_2")
        self.classInput_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.classInput_3.setGeometry(QtCore.QRect(20, 270, 201, 31))
        self.classInput_3.setObjectName("classInput_3")
        self.classInput_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.classInput_4.setGeometry(QtCore.QRect(20, 310, 201, 31))
        self.classInput_4.setObjectName("classInput_4")
        self.gradeInput_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.gradeInput_1.setGeometry(QtCore.QRect(310, 190, 71, 31))
        self.gradeInput_1.setObjectName("gradeInput_1")
        self.gradeInput_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.gradeInput_2.setGeometry(QtCore.QRect(310, 230, 71, 31))
        self.gradeInput_2.setObjectName("gradeInput_2")
        self.gradeInput_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.gradeInput_3.setGeometry(QtCore.QRect(310, 270, 71, 31))
        self.gradeInput_3.setObjectName("gradeInput_3")
        self.gradeInput_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.gradeInput_4.setGeometry(QtCore.QRect(310, 310, 71, 31))
        self.gradeInput_4.setObjectName("gradeInput_4")
        self.creditInput_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.creditInput_1.setGeometry(QtCore.QRect(480, 190, 71, 31))
        self.creditInput_1.setObjectName("creditInput_1")
        self.creditInput_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.creditInput_2.setGeometry(QtCore.QRect(480, 230, 71, 31))
        self.creditInput_2.setObjectName("creditInput_2")
        self.creditInput_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.creditInput_3.setGeometry(QtCore.QRect(480, 270, 71, 31))
        self.creditInput_3.setObjectName("creditInput_3")
        self.creditInput_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.creditInput_4.setGeometry(QtCore.QRect(480, 310, 71, 31))
        self.creditInput_4.setObjectName("creditInput_4")
        self.nameInput = QtWidgets.QTextEdit(self.centralwidget)
        self.nameInput.setGeometry(QtCore.QRect(120, 20, 161, 31))
        self.nameInput.setObjectName("nameInput")
        self.classInput_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.classInput_5.setGeometry(QtCore.QRect(20, 350, 201, 31))
        self.classInput_5.setObjectName("classInput_5")
        self.classInput_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.classInput_6.setGeometry(QtCore.QRect(20, 390, 201, 31))
        self.classInput_6.setObjectName("classInput_6")
        self.gradeInput_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.gradeInput_5.setGeometry(QtCore.QRect(310, 350, 71, 31))
        self.gradeInput_5.setObjectName("gradeInput_5")
        self.gradeInput_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.gradeInput_6.setGeometry(QtCore.QRect(310, 390, 71, 31))
        self.gradeInput_6.setObjectName("gradeInput_6")
        self.creditInput_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.creditInput_5.setGeometry(QtCore.QRect(480, 350, 71, 31))
        self.creditInput_5.setObjectName("creditInput_5")
        self.creditInput_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.creditInput_6.setGeometry(QtCore.QRect(480, 390, 71, 31))
        self.creditInput_6.setObjectName("creditInput_6")
        self.pushCalculate = QtWidgets.QPushButton(self.centralwidget)
        self.pushCalculate.setGeometry(QtCore.QRect(200, 550, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushCalculate.setFont(font)
        self.pushCalculate.setObjectName("pushCalculate")
        self.pushClear = QtWidgets.QPushButton(self.centralwidget)
        self.pushClear.setGeometry(QtCore.QRect(330, 550, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushClear.setFont(font)
        self.pushClear.setObjectName("pushClear")
        self.labelGpa = QtWidgets.QLabel(self.centralwidget)
        self.labelGpa.setGeometry(QtCore.QRect(200, 440, 211, 81))
        self.labelGpa.setText("")
        self.labelGpa.setObjectName("labelGpa")
        self.labelNumclass = QtWidgets.QLabel(self.centralwidget)
        self.labelNumclass.setGeometry(QtCore.QRect(20, 70, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.labelNumclass.setFont(font)
        self.labelNumclass.setObjectName("labelNumclass")
        self.numClassInput = QtWidgets.QTextEdit(self.centralwidget)
        self.numClassInput.setGeometry(QtCore.QRect(210, 70, 71, 31))
        self.numClassInput.setObjectName("numClassInput")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GPA Calculator"))
        self.labelName.setText(_translate("MainWindow", "Name:"))
        self.labelCourse.setText(_translate("MainWindow", "Course Name:"))
        self.labelCredits.setText(_translate("MainWindow", "Credits:"))
        self.labelGrade.setText(_translate("MainWindow", "Letter Grade:"))
        self.pushCalculate.setText(_translate("MainWindow", "Calculate"))
        self.pushClear.setText(_translate("MainWindow", "Clear"))
        self.labelNumclass.setText(_translate("MainWindow", "Number of Classes:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
