


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(740, 728)
        Form.setMinimumSize(QtCore.QSize(740, 728))
        Form.setMaximumSize(QtCore.QSize(740, 728))
        self.creditInput_3 = QtWidgets.QTextEdit(Form)
        self.creditInput_3.setGeometry(QtCore.QRect(540, 270, 71, 31))
        self.creditInput_3.setObjectName("creditInput_3")
        self.labelCourse = QtWidgets.QLabel(Form)
        self.labelCourse.setGeometry(QtCore.QRect(80, 150, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.labelCourse.setFont(font)
        self.labelCourse.setObjectName("labelCourse")
        self.gradeInput_1 = QtWidgets.QTextEdit(Form)
        self.gradeInput_1.setGeometry(QtCore.QRect(370, 190, 71, 31))
        self.gradeInput_1.setObjectName("gradeInput_1")
        self.creditInput_5 = QtWidgets.QTextEdit(Form)
        self.creditInput_5.setGeometry(QtCore.QRect(540, 350, 71, 31))
        self.creditInput_5.setObjectName("creditInput_5")
        self.creditInput_6 = QtWidgets.QTextEdit(Form)
        self.creditInput_6.setGeometry(QtCore.QRect(540, 390, 71, 31))
        self.creditInput_6.setObjectName("creditInput_6")
        self.creditInput_2 = QtWidgets.QTextEdit(Form)
        self.creditInput_2.setGeometry(QtCore.QRect(540, 230, 71, 31))
        self.creditInput_2.setObjectName("creditInput_2")
        self.nameInput = QtWidgets.QTextEdit(Form)
        self.nameInput.setGeometry(QtCore.QRect(180, 60, 161, 31))
        self.nameInput.setObjectName("nameInput")
        self.classInput_5 = QtWidgets.QTextEdit(Form)
        self.classInput_5.setGeometry(QtCore.QRect(80, 350, 201, 31))
        self.classInput_5.setObjectName("classInput_5")
        self.classInput_6 = QtWidgets.QTextEdit(Form)
        self.classInput_6.setGeometry(QtCore.QRect(80, 390, 201, 31))
        self.classInput_6.setObjectName("classInput_6")
        self.gradeInput_4 = QtWidgets.QTextEdit(Form)
        self.gradeInput_4.setGeometry(QtCore.QRect(370, 310, 71, 31))
        self.gradeInput_4.setObjectName("gradeInput_4")
        self.labelGpa = QtWidgets.QLabel(Form)
        self.labelGpa.setGeometry(QtCore.QRect(240, 460, 211, 81))
        self.labelGpa.setText("")
        self.labelGpa.setObjectName("labelGpa")
        self.creditInput_4 = QtWidgets.QTextEdit(Form)
        self.creditInput_4.setGeometry(QtCore.QRect(540, 310, 71, 31))
        self.creditInput_4.setObjectName("creditInput_4")
        self.pushCalculate = QtWidgets.QPushButton(Form)
        self.pushCalculate.setGeometry(QtCore.QRect(260, 590, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushCalculate.setFont(font)
        self.pushCalculate.setObjectName("pushCalculate")
        self.pushClear = QtWidgets.QPushButton(Form)
        self.pushClear.setGeometry(QtCore.QRect(390, 590, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushClear.setFont(font)
        self.pushClear.setObjectName("pushClear")
        self.classInput_1 = QtWidgets.QTextEdit(Form)
        self.classInput_1.setGeometry(QtCore.QRect(80, 190, 201, 31))
        self.classInput_1.setObjectName("classInput_1")
        self.classInput_3 = QtWidgets.QTextEdit(Form)
        self.classInput_3.setGeometry(QtCore.QRect(80, 270, 201, 31))
        self.classInput_3.setObjectName("classInput_3")
        self.gradeInput_5 = QtWidgets.QTextEdit(Form)
        self.gradeInput_5.setGeometry(QtCore.QRect(370, 350, 71, 31))
        self.gradeInput_5.setObjectName("gradeInput_5")
        self.classInput_2 = QtWidgets.QTextEdit(Form)
        self.classInput_2.setGeometry(QtCore.QRect(80, 230, 201, 31))
        self.classInput_2.setObjectName("classInput_2")
        self.labelGrade = QtWidgets.QLabel(Form)
        self.labelGrade.setGeometry(QtCore.QRect(350, 160, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.labelGrade.setFont(font)
        self.labelGrade.setObjectName("labelGrade")
        self.classInput_4 = QtWidgets.QTextEdit(Form)
        self.classInput_4.setGeometry(QtCore.QRect(80, 310, 201, 31))
        self.classInput_4.setObjectName("classInput_4")
        self.labelName = QtWidgets.QLabel(Form)
        self.labelName.setGeometry(QtCore.QRect(80, 60, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.labelName.setFont(font)
        self.labelName.setObjectName("labelName")
        self.creditInput_1 = QtWidgets.QTextEdit(Form)
        self.creditInput_1.setGeometry(QtCore.QRect(540, 190, 71, 31))
        self.creditInput_1.setObjectName("creditInput_1")
        self.gradeInput_6 = QtWidgets.QTextEdit(Form)
        self.gradeInput_6.setGeometry(QtCore.QRect(370, 390, 71, 31))
        self.gradeInput_6.setObjectName("gradeInput_6")
        self.gradeInput_3 = QtWidgets.QTextEdit(Form)
        self.gradeInput_3.setGeometry(QtCore.QRect(370, 270, 71, 31))
        self.gradeInput_3.setObjectName("gradeInput_3")
        self.labelCredits = QtWidgets.QLabel(Form)
        self.labelCredits.setGeometry(QtCore.QRect(540, 160, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.labelCredits.setFont(font)
        self.labelCredits.setObjectName("labelCredits")
        self.gradeInput_2 = QtWidgets.QTextEdit(Form)
        self.gradeInput_2.setGeometry(QtCore.QRect(370, 230, 71, 31))
        self.gradeInput_2.setObjectName("gradeInput_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelCourse.setText(_translate("Form", "Course Name:"))
        self.pushCalculate.setText(_translate("Form", "Calculate"))
        self.pushClear.setText(_translate("Form", "Clear"))
        self.labelGrade.setText(_translate("Form", "Letter Grade:"))
        self.labelName.setText(_translate("Form", "Name:"))
        self.labelCredits.setText(_translate("Form", "Credits:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
